### ISSUE TITLE
Support Multiple Projects in Ingestion and MCP Server

### ISSUE THREAD

**Issue by martin-papy** [martin-papy/qdrant-loader#20]
# Support Multiple Projects in Ingestion and MCP Server

## 🎯 Objective

Enable users to manage multiple projects using a single configuration file, one Qdrant server, and one MCP server instance. This will allow users to search for information within a specific project or across multiple projects seamlessly.

## 📋 Current State

Currently, the system operates with a single project scope:
- **Ingestion**: All sources are ingested into a single Qdrant collection
- **MCP Server**: Searches across all documents in the collection without project-level filtering
- **Configuration**: Single `config.yaml` file with global settings and source configurations

### 1. Configuration Structure Enhancement

Extend the configuration to support multiple projects:

```yaml
# Global configuration (shared across all projects)
global:
  qdrant:
    url: "http://localhost:6333"
    api_key: null
  embedding:
    model: "text-embedding-3-small"
    # ... other global settings

# Project-specific configurations
projects:
  project-alpha:
    display_name: "Project Alpha - Customer Portal"
    description: "Customer-facing portal documentation and code"
    collection_name: "project_alpha_docs"  # Optional: custom collection name
    sources:
      git:
        frontend-repo:
          base_url: "https://github.com/company/alpha-frontend.git"
          # ... source config
      confluence:
        alpha-space:
          space_key: "ALPHA"
          # ... source config
  
  project-beta:
    display_name: "Project Beta - Internal Tools"
    description: "Internal tooling and infrastructure"
    collection_name: "project_beta_docs"
    sources:
      git:
        tools-repo:
          base_url: "https://github.com/company/beta-tools.git"
          # ... source config
      jira:
        beta-project:
          project_key: "BETA"
          # ... source config

# Legacy support: sources at root level map to default project
sources:
  # Existing configuration for backward compatibility
```

#### Document Metadata
- Add `project_id` field to all ingested documents
- Include project metadata in document payloads
- Support project-specific chunking and embedding settings

#### CLI Enhancements
```bash
# Ingest all projects
qdrant-loader ingest

# Ingest specific project
qdrant-loader ingest --project project-alpha

# Ingest specific source within a project
qdrant-loader ingest --project project-alpha --source-type git --source frontend-repo

# List projects
qdrant-loader projects list

# Project status
qdrant-loader projects status --project project-alpha
```

#### Collection Strategy Options
1. **Single Collection with Project Filtering** (Recommended)
   - All projects in one collection with `project_id` metadata
   - Efficient cross-project search
   - Simpler Qdrant management

2. **Multiple Collections**
   - Separate collection per project
   - Better isolation but more complex management
   - Optional for users who prefer strict separation

#### New Search Parameters
```json
{
  "query": "authentication implementation",
  "project_ids": ["project-alpha", "project-beta"],  // Optional: filter by projects
  "limit": 10
}
```

#### Enhanced Search Tools
- **`search`**: Add optional `project_ids` parameter
- **`hierarchy_search`**: Add project-aware hierarchy filtering
- **`attachment_search`**: Add project-scoped attachment discovery
- **`project_search`**: New tool for project-specific searches

#### Project Management Tools
- **`list_projects`**: List available projects with metadata
- **`get_project_info`**: Get detailed project information
- **`search_across_projects`**: Explicitly search across multiple projects

#### Document Metadata
```sql
-- Add project_id to existing tables
ALTER TABLE documents ADD COLUMN project_id TEXT;
ALTER TABLE document_chunks ADD COLUMN project_id TEXT;

-- Create project metadata table
CREATE TABLE projects (
    id TEXT PRIMARY KEY,
    display_name TEXT NOT NULL,
    description TEXT,
    collection_name TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for efficient project filtering
CREATE INDEX idx_documents_project_id ON documents(project_id);
CREATE INDEX idx_document_chunks_project_id ON document_chunks(project_id);
```

### Phase 1: Configuration and Core Infrastructure
- [ ] Extend configuration schema to support projects
- [ ] Update configuration validation and parsing
- [ ] Implement backward compatibility for existing configs
- [ ] Add project metadata to document ingestion pipeline

### Phase 2: Ingestion Enhancements
- [ ] Update all connectors to include project metadata
- [ ] Enhance CLI with project-specific commands
- [ ] Implement project-aware state management
- [ ] Add database migration for existing installations

### Phase 3: MCP Server Enhancements
- [ ] Add project filtering to existing search tools
- [ ] Implement new project management tools
- [ ] Update search engine to handle project-scoped queries
- [ ] Enhance result formatting with project context

### Phase 4: Documentation and Testing
- [ ] Update documentation with multi-project examples
- [ ] Add comprehensive test coverage for multi-project scenarios
- [ ] Create migration guide for existing users
- [ ] Add example configurations for common use cases

## 🎯 Benefits

1. **Organizational Clarity**: Clear separation of different projects and their documentation
2. **Flexible Search**: Search within specific projects or across all projects
3. **Scalability**: Support for organizations with multiple products/projects
4. **Resource Efficiency**: Single Qdrant instance and MCP server for all projects
5. **Backward Compatibility**: Existing configurations continue to work

## 🔍 Use Cases

1. **Multi-Product Company**: Separate documentation for different products
2. **Client Projects**: Isolate client-specific documentation and code
3. **Development Stages**: Separate dev, staging, and production documentation
4. **Team Organization**: Department or team-specific knowledge bases
5. **Cross-Project Research**: Search across related projects for common patterns

## 📝 Acceptance Criteria

- [ ] Users can define multiple projects in a single configuration file
- [ ] Each project can have its own sources and settings
- [ ] Ingestion supports project-specific metadata and filtering
- [ ] MCP server can search within specific projects or across all projects
- [ ] Existing single-project configurations continue to work without changes
- [ ] CLI provides project management and status commands
- [ ] Documentation includes comprehensive multi-project examples

## 🏷️ Labels

- `enhancement`
- `configuration`
- `ingestion`
- `mcp-server`
- `breaking-change` (potentially, but with backward compatibility)

---

This enhancement will significantly improve the flexibility and scalability of the qdrant-loader system for organizations managing multiple projects or products.
